### ISSUE TITLE
Publish to FDroid

### ISSUE THREAD

**Issue by JakeGonder** [RayLeaf-Studios/PocketPlan#14]

**Comment by strider72** [comment]
FYI — F-Droid c;miles its own binaries from public source code. Therefore everything needs to be available from e.g. GitHub.  If anything is missing or proprietary etc, it won't work on F-Droid.

Having said that, I hope it's on FD soon. I prefer to be off the Google Store. :-)

**Comment by IzzySoft** [comment]
If the APK file were attached to `releases/`, I could make it available via [my repo](https://apt.izzysoft.de/fdroid) quickly :wink:

**Comment by JakeGonder** [comment]
@IzzySoft I attached the signed binaries to the latest release, so you are welcome to add the app to your repository. Do you automatically update the apks in your repo to the newest release of the repository?

**Comment by IzzySoft** [comment]
Thanks @JakeGonder – will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.pocket_plan.j7_003) with the next sync around 19:00 UTC! And yes: within 24h of your creating a new tag and attaching an APK to it, it will be picked up automatically (as long as you keep your "tagging scheme", i.e. continue to name the tags `v.<versionName>`, and have the `versionCode` increased).

Please take a look at the listing when it's available. If you need any adjustments, just let me know. If you like what you see, be welcome to give that Google Play badge in the Readme a sibling: pick the [IzzyOnDroid badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link it to the above URL :smiley: Further, I gladly provide you the metadata (which I pulled from Play) in [Fastlane format](https://gitlab.com/-/snippets/1895688) via a PR, so you can control how your app is presented. Fastlane would also be requested by F-Droid (once you go there), and can also be used to deploy your app to Play if you like (hence the full name "Fastlane Supply" :wink:); only for this task you'd need the Fastlane binaries, for F-Droid and for my repo the metadata files fully suffice.

**Comment by JakeGonder** [comment]
Awesome, i added your badge already. Fastlane is [one of the reasons](https://gitlab.com/fdroid/rfp/-/issues/1989) why we didn't add our app to F-Droid directly yet. We will gladly accept your PR with the Fastlane metadata.

**Comment by IzzySoft** [comment]
Thanks – and there you go!

**Comment by IzzySoft** [comment]
Looks like you forgot to update `versionCode` and `versionName`: the APK at the latest release differs from the previous one, but still identifies with the same values. Please take care to always increase the values **before** tagging the release and building the corresponding APK. I see version is increased **now** (and at the release tag) – but that was most likely after the APK has been built.

**Comment by JakeGonder** [comment]
My mistake, i only rebuilt the app bundle for the playstore, and then uploaded the entire release folder, including the old apk and the new app bundle, will fix this soon.

**Comment by JakeGonder** [comment]
I attached the correct binaries now, hope this did not create too much of an inconvenience on your side.

**Comment by IzzySoft** [comment]
Thanks a lot! I've just triggered the update manually (worked fine) and then replaced the original 1.3.5 from the quarantine (where the updater had moved it when the not-1.3.6 claimed to be 1.3.5, too) – so with the next sync today all should be fine again. All existing users will receive an update notification then.
