### ISSUE TITLE
Bug: All shopping items in a category are checked when moving a category below a checked category, even if "move checked categories down" is disabled

### ISSUE THREAD

**Issue by johnsgp** [RayLeaf-Studios/PocketPlan#67]
I wanted to change the order of the categories so started dragging them around. Without realising it, this was checking all the items on the lcategory. I've now lost track of what was unchecked. Can categories be moved without auto-checking items? (Is this a bug or feature request? I've called it a bug because it was totally unexpected.)

**Comment by JakeGonder** [comment]
Fixed with [release 1.4.1](https://github.com/RayLeaf-Studios/PocketPlan/releases/tag/v.1.4.1)
